site_name: SynthShapes
nav:
  - Home: index.md
  - Quick Start: quickstart.md
  - API:
    - SynthShapes: api/SynthShapes.md
    - SynthShapes.blending: api/blending.md
    - SynthShapes.filters: api/filters.md
    - SynthShapes.hist: api/hist.md
    - SynthShapes.texturizing: api/texturizing.md
    - SynthShapes.shapes: api/shapes.md
    
theme: material

plugins:
# - mkdocs-jupyter
- search
- autorefs
- mkdocstrings:
    handlers:
      python:
        paths: [.]
        import:
        - https://pytorch.org/docs/stable/objects.inv
        - https://numpy.org/doc/stable/objects.inv
        options:
          docstring_style: numpy
          docstring_section_style: spacy
          docstring_options:
            allow_section_blank_line: True
          merge_init_into_class: True
          separate_signature: True
          members_order: source
          show_source: True
          show_root_heading: True

### Markdown stuff
markdown_extensions:
- admonition
- toc:
    toc_depth: 3
# - markdown_grid_tables
- pymdownx.details
- pymdownx.superfences
- pymdownx.highlight:
    anchor_linenums: true
    line_spans: __span
    pygments_lang_class: true
- pymdownx.inlinehilite
- pymdownx.snippets
- pymdownx.arithmatex:
    generic: true
- pymdownx.superfences:
    custom_fences:
    - name: mermaid
      class: mermaid
      format: !!python/name:pymdownx.superfences.fence_code_format
- pymdownx.superfences
- pymdownx.tabbed:
    alternate_style: true
    slugify: !!python/object/apply:pymdownx.slugs.slugify
      kwds:
        case: lower