site_name: SynthShapes
repo_url: https://github.com/EtienneChollet/SynthShapes/
site_dir: html
docs_dir: docs
theme:
  name: material

plugins:
  - search
  - mkdocstrings

nav:
  - Home: index.md
  - API Reference: api.md